In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.mixture import GaussianMixture
from sklearn import metrics

In [3]:
def purity(clusters,y,labels):
    purity = 0
    for k in range(5):
        labelcounts = np.zeros(len(labels))
        print(purity)
        for i in range(len(clusters)):
            if clusters[i] == k:
                labelcounts[labels.index(y[i])] = labelcounts[labels.index(y[i])] +1
        print(labelcounts)
        purity += np.max(labelcounts)
    return purity/len(y)

In [4]:
df = pd.read_csv("reducedData.csv")

In [5]:
X = df.drop('class',axis=1)
y = df['class']

In [6]:
gmm = GaussianMixture(n_components=5)
gmm.fit(X)

GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=100,
        means_init=None, n_components=5, n_init=1, precisions_init=None,
        random_state=None, reg_covar=1e-06, tol=0.001, verbose=0,
        verbose_interval=10, warm_start=False, weights_init=None)

In [7]:
clusters = gmm.predict(X)

In [8]:
purity(clusters,y,list(y.unique()))

0
[9673. 1388.  355. 4097.   17.]
9673.0
[    0. 31915.     0.     0.     0.]
41588.0
[0. 0. 0. 4. 0.]
41592.0
[5.5821e+04 1.0173e+04 4.7800e+02 1.8720e+03 1.1000e+01]
97413.0
[1849. 2451.  162. 5683.   24.]


0.8183975931350369