In [1]:
import numpy as np
import pandas as pd
from copy import deepcopy

In [2]:
df = pd.read_csv("reducedData.csv")

In [3]:
X = df.drop('class',axis=1)
y = df['class']

In [4]:
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [5]:
def euclidean(v1,v2):
    ary = spatial.distance.cdist(v1,v2, metric='minkowski')
    return ary[0,0]

In [6]:
def distances(a,b):
    return np.linalg.norm(a - b, axis=1)

In [7]:
def safe_div(x,y):
    if y == 0:
        return 0
    return x / y

In [8]:
def purity(clusters,y,labels):
    purity = 0
    for k in range(5):
        labelcounts = np.zeros(len(labels))
        print(purity)
        for i in range(len(clusters)):
            if clusters[i] == k:
                labelcounts[labels.index(y[i])] = labelcounts[labels.index(y[i])] +1
        print(labelcounts)
        purity += np.max(labelcounts)
    return purity/len(y)

In [9]:
k = 5
centroids = np.asarray(X[:5])
centroids_old = np.zeros(centroids.shape)

In [10]:
error = distances(centroids, centroids_old)
error.mean()
X = np.asarray(X)

In [11]:
clusters = np.zeros(len(X))
for ite in range(10):
    for i in range(len(X)):
        distance = distances(X[i], centroids)
        cluster = np.argmin(distance)
        clusters[i] = cluster
    centroids_old = deepcopy(centroids)
    for i in range(k):
        points = [X[j] for j in range(len(X)) if clusters[j] == i]
        centroids[i] = np.mean(points, axis=0)
    error = distances(centroids,centroids_old)

In [12]:
clusters

array([0., 1., 2., ..., 4., 2., 4.])

In [13]:
y.unique()

array(['normal', 'dos', 'r2l', 'probe', 'u2r'], dtype=object)

In [14]:
purity(clusters,y,list(y.unique()))

0
[2838. 6899.   49. 1221.    0.]
6899.0
[2.203e+03 1.280e+02 1.000e+00 4.934e+03 1.000e+00]
11833.0
[1.350e+02 3.431e+04 2.000e+00 3.190e+02 0.000e+00]
46143.0
[23710.   425.   589.  4589.    43.]
69853.0
[3.8457e+04 4.1650e+03 3.5400e+02 5.9300e+02 8.0000e+00]


0.8597874147634811