In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cluster import AgglomerativeClustering

In [2]:
def purity(clusters,y,labels):
    purity = 0
    for k in range(5):
        labelcounts = np.zeros(len(labels))
        print(purity)
        for i in range(len(clusters)):
            if clusters[i] == k:
                labelcounts[labels.index(y[i])] = labelcounts[labels.index(y[i])] +1
        print(labelcounts)
        purity += np.max(labelcounts)
    return purity/len(y)

In [3]:
df = pd.read_csv("reducedData.csv")

In [4]:
X = df.drop('class',axis=1)
y = df['class']
len(X)

125973

In [5]:
cluster = AgglomerativeClustering(n_clusters=5, affinity='euclidean', linkage='single')  
clusters = cluster.fit_predict(X[:20000])  

In [6]:
purity(clusters,y[:20000],list(y.unique()))

0
[10686.  7346.   159.  1790.    11.]
10686.0
[5. 0. 0. 0. 0.]
10691.0
[1. 0. 0. 0. 0.]
10692.0
[0. 0. 0. 1. 0.]
10693.0
[1. 0. 0. 0. 0.]


0.5347