In [10]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.mixture import GaussianMixture
from sklearn import metrics

In [11]:
def purity(clusters,y,labels):
    for k in range(5):
        purity = 0
        labelcounts = np.zeros(len(labels))
        for i in range(len(clusters)):
            if clusters[i] == k:
                labelcounts[labels.index(y[i])] = labelcounts[labels.index(y[i])] +1
        print(labelcounts)
        purity = np.max(labelcounts)/ np.sum(labelcounts)
        print(purity)

In [12]:
df_a = pd.read_csv("../input_data/reducedData_a.csv")
df_b = pd.read_csv("../input_data/reducedData_b.csv")

In [13]:
X_a = df_a.drop('class',axis=1)
y_a = df_a['class']
X_b = df_b.drop('class',axis=1)
y_b = df_b['class']

In [14]:
X_a.shape

(125973, 14)

# Reduced data B, 
due to large values in A, gmm throwed error

In [16]:
gmm = GaussianMixture(n_components=5)
gmm.fit(X_b)
clusters = gmm.predict(X_b)
purity(clusters,y_b,list(y_b.unique()))

[11498. 11343.   444.  7216.    12.]
0.37682299347818965
[0. 0. 0. 4. 0.]
1.0
[4.164e+04 2.282e+03 3.840e+02 4.145e+03 9.000e+00]
0.8592653735039207
[14205.   799.   167.   291.    31.]
0.9168656812754147
[    0. 31503.     0.     0.     0.]
1.0
