In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cluster import AgglomerativeClustering

In [2]:
def purity(clusters,y,labels):
    for k in range(5):
        purity = 0
        labelcounts = np.zeros(len(labels))
        for i in range(len(clusters)):
            if clusters[i] == k:
                labelcounts[labels.index(y[i])] = labelcounts[labels.index(y[i])] +1
        print(labelcounts)
        purity = np.max(labelcounts)/ np.sum(labelcounts)
        print(purity)

In [3]:
df_a = pd.read_csv("../input_data/reducedData_a.csv")
df_b = pd.read_csv("../input_data/reducedData_b.csv")

In [4]:
X_a = df_a.drop('class',axis=1)
y_a = df_a['class']
X_b = df_b.drop('class',axis=1)
y_b = df_b['class']

In [5]:
cluster = AgglomerativeClustering(n_clusters=5, affinity='euclidean', linkage='single')  
clusters = cluster.fit_predict(X_a[:20000])  

In [6]:
purity(clusters,y_a[:20000],list(y_a.unique()))

[0. 0. 0. 9. 0.]
1.0
[10692.  7345.   159.  1761.    11.]
0.5354567307692307
[0. 0. 0. 9. 0.]
1.0
[1. 1. 0. 0. 0.]
0.5
[ 0.  0.  0. 12.  0.]
1.0


In [7]:
cluster = AgglomerativeClustering(n_clusters=5, affinity='euclidean', linkage='single')  
clusters = cluster.fit_predict(X_b[:20000])  

In [8]:
purity(clusters,y_b[:20000],list(y_b.unique()))

[10687.  7346.   159.  1790.    11.]
0.5345370879807932
[1. 0. 0. 0. 0.]
1.0
[4. 0. 0. 0. 0.]
1.0
[0. 0. 0. 1. 0.]
1.0
[1. 0. 0. 0. 0.]
1.0
