In [31]:
import numpy as np
import pandas as pd
from copy import deepcopy

In [32]:
df_a = pd.read_csv("../input_data/reducedData_a.csv")

In [33]:
df_b = pd.read_csv("../input_data/reducedData_b.csv")

In [34]:
X_a = df_a.drop('class',axis=1)
y_a = df_a['class']

In [35]:
X_b = df_b.drop('class',axis=1)
y_b = df_b['class']

In [36]:
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [37]:
def euclidean(v1,v2):
    ary = spatial.distance.cdist(v1,v2, metric='minkowski')
    return ary[0,0]

In [38]:
def distances(a,b):
    return np.linalg.norm(a - b, axis=1)

In [39]:
def safe_div(x,y):
    if y == 0:
        return 0
    return x / y

In [40]:
def purity(clusters,y,labels):
    for k in range(5):
        purity = 0
        labelcounts = np.zeros(len(labels))
        for i in range(len(clusters)):
            if clusters[i] == k:
                labelcounts[labels.index(y[i])] = labelcounts[labels.index(y[i])] +1
        print(labelcounts)
        purity = np.max(labelcounts)/ np.sum(labelcounts)
        print(purity)

In [41]:
k = 5
centroids = np.asarray(X_a[:5])
centroids_old = np.zeros(centroids.shape)

In [42]:
error = distances(centroids, centroids_old)
error.mean()
X_a = np.asarray(X_a)

In [43]:
clusters = np.zeros(len(X_a))
for ite in range(10):
    for i in range(len(X_a)):
        distance = distances(X_a[i], centroids)
        cluster = np.argmin(distance)
        clusters[i] = cluster
    centroids_old = deepcopy(centroids)
    for i in range(k):
        points = [X_a[j] for j in range(len(X_a)) if clusters[j] == i]
        centroids[i] = np.mean(points, axis=0)
    error = distances(centroids,centroids_old)

In [44]:
clusters

array([0., 1., 2., ..., 4., 2., 4.])

In [45]:
purity(clusters,y_a,list(y_a.unique()))

[4.961e+03 6.490e+02 1.600e+01 1.349e+03 4.000e+00]
0.7108468261928643
[2762. 6894.   49. 5254.    0.]
0.4608596831338993
[9.5000e+01 3.4312e+04 3.0000e+00 2.9500e+02 0.0000e+00]
0.9886759832877107
[4.0467e+04 1.0370e+03 5.5300e+02 4.1070e+03 1.5000e+01]
0.8763074124602092
[19058.  3035.   374.   651.    33.]
0.8232041812448706


In [48]:
# Reduced data B

In [51]:
centroids = np.asarray(X_b[:5])
centroids_old = np.zeros(centroids.shape)
error = distances(centroids, centroids_old)
error.mean()
X_b = np.asarray(X_b)
clusters = np.zeros(len(X_b))
for ite in range(10):
    for i in range(len(X_b)):
        distance = distances(X_b[i], centroids)
        cluster = np.argmin(distance)
        clusters[i] = cluster
    centroids_old = deepcopy(centroids)
    for i in range(k):
        points = [X_b[j] for j in range(len(X_b)) if clusters[j] == i]
        centroids[i] = np.mean(points, axis=0)
    error = distances(centroids,centroids_old)

In [52]:
purity(clusters,y_b,list(y_b.unique()))

[5.580e+02 6.894e+03 1.000e+00 3.347e+03 2.000e+00]
0.6382151453434549
[3.079e+03 2.440e+02 9.100e+01 3.178e+03 3.000e+00]
0.4818802122820318
[2.4600e+02 3.5788e+04 5.0000e+00 2.2700e+02 1.0000e+00]
0.9867924008051396
[23629.   629.   608.  4567.    39.]
0.8017440282301845
[3.9831e+04 2.3720e+03 2.9000e+02 3.3700e+02 7.0000e+00]
0.9298270186987885
